### ISSUE TITLE
Supports

### ISSUE THREAD

**Issue by jemshit** [TurhanOz/ReactiveDirectoryChooser#3]
Does this support to choose file from external SdCard, internal storage,Google drive and Dropbox ?

**Comment by TurhanOz** [comment]
When instantiating the ReactiveDirectoryChooser (RDC) fragment, you can pass a File as an argument (that will be displayed first), as follow : 
DialogFragment directoryChooserFragment = DirectoryChooserFragment.newInstance(rootDirectory);

This rootDirectory could be any File you want : 
- external Storage Directory : Environment.getExternalStorageDirectory()
- external Cache Directory : getExternalCacheDir()
- any External File Directories : getExternalFilesDir()
- any Directory File accessible...

Regarding Google Drive and Dropbox, they are not supported by the RDC as they have dedicated API : 
- https://developers.google.com/drive/android/
- https://www.dropbox.com/developers/core/sdks/android

**Comment by jemshit** [comment]
ok
