### ISSUE TITLE
ic_launcher.png: error: Duplicate file

### ISSUE THREAD

**Issue by flavioelawi** [TurhanOz/ReactiveDirectoryChooser#4]
Your library does not need ic_launcher.png. Including it causes build errors such as this:
`build/intermediates/res/debug/mipmap-mdpi/ic_launcher.png: error: Duplicate file.`
Please remove it from your library.

**Comment by TurhanOz** [comment]
#1 have you tried to clean and rebuild your project ?
(gradle clean build assemble)

#2 restaring android studio ?

**Comment by flavioelawi** [comment]
yes, i tried #1 and #2 with no success.
Actually i was able to build my project by downloading the aar archive file from maven central and removing the mipmap-mdpi folders from it.

**Comment by TurhanOz** [comment]
@flavioelawi new version 0.0.12 available on maven central in few minutes, let me know if it fixes your need. Cheers
